export const mockTours = [
    {
        _id: '1',
        title: 'Vatican Museums & Sistine Chapel Guided Tour',
        slug: { current: 'vatican-museums-and-sistine-chapel-guided-tour' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&q=80' } },
        price: 65,
        duration: '2 Hours',
        description: 'Skip the long lines and step directly into the extraordinary world of the Vatican Museums with an expert guide.',
        category: 'Guided',
        features: ['Skip the Line', 'Expert Guide', 'Sistine Chapel'],
    },
    {
        _id: '2',
        title: 'Vatican Museums and Sistine Chapel Skip-the-Line Ticket',
        slug: { current: 'vatican-museums-sistine-chapel-skip-the-line' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&q=80' } },
        price: 45,
        duration: '3 Hours',
        description: 'Experience the Vatican Museums and Sistine Chapel at your own pace with priority access.',
        category: 'Ticket',
        features: ['Priority Access', 'Self-Guided', 'Instant Confirmation'],
    },
    {
        _id: '3',
        title: "St. Peter's Basilica & Dome Climb",
        slug: { current: 'st-peters-basilica-dome-climb' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1555523179-c5c830c23932?auto=format&fit=crop&q=80' } },
        price: 35,
        duration: '2 Hours',
        description: "Climb to the top of Michelangelo's Dome for the best view in Rome, followed by a guided tour of the Basilica.",
        category: 'Basilica',
        features: ['Dome Ticket', 'Guided Tour', 'Panoramic Views'],
    },
    {
        _id: '4',
        title: 'Vatican Gardens Bus Tour',
        slug: { current: 'vatican-gardens-bus-tour' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1596707323565-385038ec8891?auto=format&fit=crop&q=80' } },
        price: 55,
        duration: '1.5 Hours',
        description: 'Discover the lush, hidden gardens of the Vatican State on an eco-friendly open bus tour.',
        category: 'Gardens',
        features: ['Audio Guide', 'Eco Bus', 'Hidden Gems'],
    },
    {
        _id: '5',
        title: 'Castel Sant\'Angelo Fast Track',
        slug: { current: 'castel-sant-angelo-fast-track' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1525874684015-58379d421a52?auto=format&fit=crop&q=80' } },
        price: 28,
        duration: '2 Hours',
        description: 'Explore the Mausoleum of Hadrian adjacent to the Vatican with panoramic terrace views.',
        category: 'History',
        features: ['Fast Track', 'Self-Guided', 'River Views'],
    },
    {
        _id: '6',
        title: 'Vatican Night Tour: Under the Stars',
        slug: { current: 'vatican-night-tour' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&q=80' } },
        price: 75,
        duration: '3 Hours',
        description: 'A magical evening experience visiting the museums after sunset with fewer crowds.',
        category: 'Special',
        features: ['Night Access', 'Less Crowded', 'Guide Included'],
    }
];
