export const mockTours = [
    {
        _id: '1',
        title: 'Vatican Museums & Sistine Chapel: Fast Track',
        slug: { current: 'vatican-museums-sistine-chapel-fast-track' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1542820229-081e0c12af0b?auto=format&fit=crop&q=80' } },
        price: 45,
        duration: '2.5 Hours',
        description: 'Skip the long lines and enter the Vatican Museums with priority. Admire the Gallery of Maps and the Sistine Chapel.',
        category: 'Museums',
        features: ['Skip the Line', 'Headsets Included', 'Instant Confirmation'],
    },
    {
        _id: '2',
        title: 'Early Morning Private Vatican Tour',
        slug: { current: 'early-morning-private-vatican-tour' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1582260659695-17d12f300ca7?auto=format&fit=crop&q=80' } },
        price: 120,
        duration: '3.5 Hours',
        description: 'Experience the Sistine Chapel in peace before the general public arrives. A truly exclusive experience.',
        category: 'Private',
        features: ['Early Access', 'Private Guide', 'Pickup Included'],
    },
    {
        _id: '3',
        title: "St. Peter's Basilica & Dome Climb",
        slug: { current: 'st-peters-basilica-dome-climb' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1555523179-c5c830c23932?auto=format&fit=crop&q=80' } },
        price: 35,
        duration: '2 Hours',
        description: "Climb to the top of Michelangelo's Dome for the best view in Rome, followed by a guided tour of the Basilica.",
        category: 'Basilica',
        features: ['Dome Ticket', 'Guided Tour', 'Panoramic Views'],
    },
    {
        _id: '4',
        title: 'Vatican Gardens Bus Tour',
        slug: { current: 'vatican-gardens-bus-tour' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1596707323565-385038ec8891?auto=format&fit=crop&q=80' } },
        price: 55,
        duration: '1.5 Hours',
        description: 'Discover the lush, hidden gardens of the Vatican State on an eco-friendly open bus tour.',
        category: 'Gardens',
        features: ['Audio Guide', 'Eco Bus', 'Hidden Gems'],
    },
    {
        _id: '5',
        title: 'Castel Sant\'Angelo Fast Track',
        slug: { current: 'castel-sant-angelo-fast-track' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1525874684015-58379d421a52?auto=format&fit=crop&q=80' } },
        price: 28,
        duration: '2 Hours',
        description: 'Explore the Mausoleum of Hadrian adjacent to the Vatican with panoramic terrace views.',
        category: 'History',
        features: ['Fast Track', 'Self-Guided', 'River Views'],
    },
    {
        _id: '6',
        title: 'Vatican Night Tour: Under the Stars',
        slug: { current: 'vatican-night-tour' },
        mainImage: { asset: { url: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&q=80' } },
        price: 75,
        duration: '3 Hours',
        description: 'A magical evening experience visiting the museums after sunset with fewer crowds.',
        category: 'Special',
        features: ['Night Access', 'Less Crowded', 'Guide Included'],
    }
];
