export type TourProduct = {
    id: string;
    title: string;
    slug: string;
    category: 'colosseum' | 'vatican' | 'city' | 'hidden-gems';
    tourType: string;
    price: number;
    duration: string;
    description: string;
    highlights: string[];
    includes: string[];
    imageUrl: string;
    badge?: string;
    rating: number;
    reviews: number;
};

// Working Unsplash image URLs for Rome tours
export const tours: TourProduct[] = [
    // --- VATICAN & RELIGIOUS ---
    {
        id: 'vatican-museums-sistine',
        title: 'Vatican Museums & Sistine Chapel Skip-the-Line',
        slug: 'vatican-museums-sistine-chapel',
        category: 'vatican',
        tourType: 'Guided Tour',
        price: 65,
        duration: '2.5 hours',
        description: "Skip the line to visit the Vatican Museums and Sistine Chapel. Marvel at Michelangelo's masterpieces and explore the Gallery of Maps and Raphael Rooms with an expert guide.",
        highlights: ['Skip-the-line entry', 'Sistine Chapel', 'Raphael Rooms', 'Gallery of Maps'],
        includes: ['Expert Guide', 'Entrance Tickets', 'Headsets'],
        imageUrl: 'https://images.unsplash.com/photo-1541185933-710f50b90c28?w=800&q=80',
        badge: 'Bestseller',
        rating: 4.9,
        reviews: 1240
    },
    {
        id: 'st-peters-dome-climb',
        title: "St. Peter's Basilica Dome Climb",
        slug: 'st-peters-basilica-dome-climb',
        category: 'vatican',
        tourType: 'Adventure',
        price: 35,
        duration: '1.5 hours',
        description: "Climb to the top of Michelangelo's Dome for the best view in Rome. Explore the interior of the Basilica and see the Pietà and Baldachin from a unique perspective.",
        highlights: ['Dome Climb', 'Panoramic Views', 'Basilica Interior', 'Papal Tombs View'],
        includes: ['Dome Ticket', 'Guide', 'Elevator Access (partial)'],
        imageUrl: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=800&q=80',
        badge: 'Must Do',
        rating: 4.8,
        reviews: 850
    },
    {
        id: 'vatican-gardens-bus',
        title: 'Vatican Gardens Open Bus & Museums',
        slug: 'vatican-gardens-open-bus',
        category: 'vatican',
        tourType: 'Bus Tour',
        price: 95,
        duration: '3 hours',
        description: 'Explore the exclusive Vatican Gardens by eco-friendly open bus, then enjoy skip-the-line access to the Vatican Museums and Sistine Chapel at your own pace.',
        highlights: ['Vatican Gardens', 'Open Bus Ride', 'Sistine Chapel', 'Museum Access'],
        includes: ['Bus Tour', 'Audio Guide', 'Museum Ticket'],
        imageUrl: 'https://images.unsplash.com/photo-1525874684015-58379d421a52?w=800&q=80',
        rating: 4.7,
        reviews: 320
    },
    {
        id: 'vatican-gardens-vip',
        title: 'VIP Vatican Gardens & Museums Guided Tour',
        slug: 'vip-vatican-gardens-guided',
        category: 'vatican',
        tourType: 'Private/Small Group',
        price: 115,
        duration: '4 hours',
        description: "An exclusive walking tour of the Vatican Gardens, followed by a guided visit to the Museums and Sistine Chapel. Experience the Vatican in peace and luxury.",
        highlights: ['Private Gardens Walk', 'Sistine Chapel', 'No Crowds', 'Expert Narrative'],
        includes: ['VIP Entry', 'Private Guide', 'All Tickets'],
        imageUrl: 'https://images.unsplash.com/photo-1520556157077-f27357c37c22?w=800&q=80',
        badge: 'VIP',
        rating: 5.0,
        reviews: 150
    },
    {
        id: 'vatican-castel-combo',
        title: 'Vatican & Castel Sant\'Angelo Combo',
        slug: 'vatican-castel-sant-angelo-combo',
        category: 'vatican',
        tourType: 'Combo Tour',
        price: 130,
        duration: '5 hours',
        description: "The ultimate religious and military history tour. Visit the Vatican Museums and Sistine Chapel, then cross to Castel Sant'Angelo to see the Papal fortress and Rooftop views.",
        highlights: ['Vatican Museums', 'Castel Sant\'Angelo', 'Passetto Intro', 'Rooftop Views'],
        includes: ['All Tickets', 'Guide', 'Headsets'],
        imageUrl: 'https://images.unsplash.com/photo-1542027432438-ef349e0efd5e?w=800&q=80',
        rating: 4.8,
        reviews: 210
    },

    // --- COLOSSEUM & ANCIENT ROME ---
    {
        id: 'colosseum-underground',
        title: 'Colosseum Underground & Arena Floor',
        slug: 'colosseum-underground-arena',
        category: 'colosseum',
        tourType: 'VIP Tour',
        price: 100,
        duration: '3.5 hours',
        description: "Go beneath the arena to the Hypogeum, the gladiatorial backstage. Then walk onto the Arena Floor. Includes Forum and Palatine Hill.",
        highlights: ['Underground Access', 'Arena Floor', 'Roman Forum', 'Palatine Hill'],
        includes: ['Special Access Tickets', 'Expert Guide', 'Small Group'],
        imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
        badge: 'Sell Out',
        rating: 5.0,
        reviews: 2100
    },
    {
        id: 'colosseum-arena',
        title: 'Colosseum Arena Floor & Roman Forum',
        slug: 'colosseum-arena-floor-forum',
        category: 'colosseum',
        tourType: 'Guided Tour',
        price: 85,
        duration: '3 hours',
        description: "Step onto the reconstructed Arena Floor through the Gladiator's Gate. Enjoy a comprehensive tour of the Colosseum and the ancient city center.",
        highlights: ['Arena Floor', 'Gladiator Gate', 'Ancient Ruins', 'Forum Walk'],
        includes: ['Arena Tickets', 'Guide', 'Headsets'],
        imageUrl: 'https://images.unsplash.com/photo-1509024644558-2f56ce76c490?w=800&q=80',
        rating: 4.8,
        reviews: 1800
    },
    {
        id: 'palatine-sunrise',
        title: 'Palatine Hill Private Sunrise Tour',
        slug: 'palatine-hill-sunrise',
        category: 'colosseum',
        tourType: 'Private',
        price: 250,
        duration: '2 hours',
        description: 'Experience the birth of Rome at sunrise. Exclusive early access to Palatine Hill with a private guide. Perfect for photographers and romance.',
        highlights: ['Sunrise Views', 'Empty Ruins', 'House of Augustus', 'Circus Maximus View'],
        includes: ['Private Guide', 'Early Entry'],
        imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
        badge: 'Exclusive',
        rating: 5.0,
        reviews: 45
    },
    {
        id: 'domus-aurea',
        title: "Domus Aurea: Nero's Golden House",
        slug: 'domus-aurea-nero-golden-house',
        category: 'colosseum',
        tourType: 'Archaeology',
        price: 45,
        duration: '1.5 hours',
        description: "Descend into Emperor Nero's buried golden palace. Wear a hard hat and explore incredible frescoes and VR reconstructions of the ancient luxury.",
        highlights: ['Underground Palace', 'Ancient Frescoes', 'VR Experience', 'Archaeology'],
        includes: ['Helmet', 'Guide', 'VR Glasses'],
        imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80',
        rating: 4.7,
        reviews: 320
    },
    {
        id: 'colosseum-express',
        title: 'Colosseum Express Guided Tour',
        slug: 'colosseum-express-tour',
        category: 'colosseum',
        tourType: 'Express',
        price: 55,
        duration: '1.5 hours',
        description: "Short on time? See the Colosseum highlights with a licensed guide in just 90 minutes. Perfect introduction to the monument.",
        highlights: ['Colosseum 1st & 2nd Tier', 'History Overview', 'Fast Track'],
        includes: ['Entrance Ticket', 'Guide'],
        imageUrl: 'https://images.unsplash.com/photo-1579606038588-6e7a0f5d8363?w=800&q=80',
        rating: 4.6,
        reviews: 950
    },

    // --- CITY & WALKING TOURS ---
    {
        id: 'pantheon-guided',
        title: 'Pantheon Guided Tour: Glory of Rome',
        slug: 'pantheon-guided-tour',
        category: 'city',
        tourType: 'Walking Tour',
        price: 40,
        duration: '1 hour',
        description: "Understand the engineering miracle of the Pantheon. Visit Raphael's Tomb and stand under the massive Oculus with an expert.",
        highlights: ['Oculus', 'Raphael\'s Tomb', 'Roman Engineering'],
        includes: ['Entry Ticket', 'Guide'],
        imageUrl: 'https://images.unsplash.com/photo-1515542622106-78bda8baa0b1?w=800&q=80',
        badge: 'Bestseller',
        rating: 4.8,
        reviews: 1500
    },
    {
        id: 'historic-squares',
        title: 'Rome City Walk: Trevi, Pantheon & Navona',
        slug: 'rome-historic-squares-walking-tour',
        category: 'city',
        tourType: 'Walking Tour',
        price: 35,
        duration: '2.5 hours',
        description: "The classic 'Dolce Vita' walk. Toss a coin in the Trevi Fountain, see the Pantheon, and admire Bernini's fountains in Piazza Navona.",
        highlights: ['Trevi Fountain', 'Spanish Steps', 'Piazza Navona', 'Gelato Stop'],
        includes: ['Local Guide', 'Walking Tour'],
        imageUrl: 'https://images.unsplash.com/photo-1542027432438-ef349e0efd5e?w=800&q=80',
        rating: 4.7,
        reviews: 2200
    },
    {
        id: 'hidden-churches',
        title: 'Hidden Churches of Rome',
        slug: 'hidden-churches-walking-tour',
        category: 'hidden-gems',
        tourType: 'Culture',
        price: 50,
        duration: '2.5 hours',
        description: "Discover the secret sacred gems of Rome. Visit quiet, off-the-beaten-path churches filled with Caravaggios, relics, and ancient mosaics.",
        highlights: ['Hidden Frescoes', 'Caravaggio Art', 'Quiet Cloisters'],
        includes: ['Expert Art Historian', 'Church Entries'],
        imageUrl: 'https://images.unsplash.com/photo-1520186994203-52c8c9521c32?w=800&q=80',
        rating: 4.9,
        reviews: 180
    },
    {
        id: 'catacombs-appian',
        title: 'Appian Way & Catacombs Tour',
        slug: 'appian-way-catacombs',
        category: 'hidden-gems',
        tourType: 'Bus/Walk',
        price: 65,
        duration: '3 hours',
        description: "Journey to the ancient Appian Way. Walk on original Roman stones, see the aqueducts, and descend into the Christian Catacombs.",
        highlights: ['Catacombs', 'Ancient Appian Way', 'Aqueducts', 'Countryside'],
        includes: ['Transport', 'Catacomb Ticket', 'Guide'],
        imageUrl: 'https://images.unsplash.com/photo-1543429766-99173822d54e?w=800&q=80',
        rating: 4.7,
        reviews: 600
    },
    {
        id: 'stadium-domitian',
        title: 'Stadium of Domitian Underground',
        slug: 'stadium-of-domitian-underground',
        category: 'hidden-gems',
        tourType: 'Self-Guided',
        price: 15,
        duration: '1 hour',
        description: "Go beneath Piazza Navona to see the ruins of the ancient athletic stadium. A fascinating quick dive into Roman sports history.",
        highlights: ['Underground Ruins', 'History of Sports', 'Piazza Navona Origins'],
        includes: ['Audio Guide', 'Entry Ticket'],
        imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
        rating: 4.5,
        reviews: 410
    },
    {
        id: 'santa-maria-underground',
        title: 'Santa Maria Maggiore Underground',
        slug: 'santa-maria-maggiore-underground',
        category: 'hidden-gems',
        tourType: 'Guided Tour',
        price: 30,
        duration: '1 hour',
        description: "Explore the archaeological excavations beneath one of Rome's four major basilicas. See Roman calendar frescoes and ancient foundations.",
        highlights: ['Underground Excavations', 'Ancient Mosaics', 'Basilica History'],
        includes: ['Guide', 'Special Entry'],
        imageUrl: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=800&q=80',
        rating: 4.6,
        reviews: 120
    },
    {
        id: 'castel-sant-angelo',
        title: 'Castel Sant\'Angelo: Emperors & Popes',
        slug: 'castel-sant-angelo-guided',
        category: 'city',
        tourType: 'Guided Tour',
        price: 55,
        duration: '2 hours',
        description: "Visit the Mausoleum of Hadrian turned Fortress. Explore the Papal apartments, prison cells, and enjoy the best rooftop view of the Vatican.",
        highlights: ['Rooftop View', 'Papal Apartments', 'Passetto', 'Imperial Tomb'],
        includes: ['Skip-the-line Ticket', 'Guide'],
        imageUrl: 'https://images.unsplash.com/photo-1542027432438-ef349e0efd5e?w=800&q=80',
        rating: 4.7,
        reviews: 980
    },

    // --- SPECIAL & GOLF CART ---
    {
        id: 'golf-cart-highlights',
        title: 'Rome Highlights by Golf Cart',
        slug: 'rome-highlights-golf-cart',
        category: 'hidden-gems',
        tourType: 'Golf Cart',
        price: 150,
        duration: '3 hours',
        description: "The most fun way to see Rome! Zip through narrow streets and see the Colosseum, Trevi, Pantheon, and more without walking.",
        highlights: ['No Walking', 'Cover More Ground', 'Fun & easy', 'Major Sights'],
        includes: ['Driver/Guide', 'Golf Cart'],
        imageUrl: 'https://images.unsplash.com/photo-1529180979161-06b8b6d6f2be?w=800&q=80',
        badge: 'Trending',
        rating: 4.9,
        reviews: 550
    },
    {
        id: 'golf-cart-night',
        title: 'Rome by Night Golf Cart Tour',
        slug: 'rome-by-night-golf-cart',
        category: 'hidden-gems',
        tourType: 'Golf Cart',
        price: 160,
        duration: '2.5 hours',
        description: "See the Eternal City sparkle at night. Visit the lit-up Monuments and enjoy the romantic atmosphere of Rome after dark.",
        highlights: ['Illuminated Monuments', 'Romantic Atmosphere', 'Prosecco Stop'],
        includes: ['Driver/Guide', 'Golf Cart', 'Drink'],
        imageUrl: 'https://images.unsplash.com/photo-1529260830902-2834b127598c?w=800&q=80',
        rating: 5.0,
        reviews: 420
    },
    {
        id: 'rome-in-a-day',
        title: 'Rome in a Day: Vatican & Colosseum',
        slug: 'rome-in-a-day-private',
        category: 'hidden-gems',
        tourType: 'Private/Combo',
        price: 450,
        duration: '7 hours',
        description: "The complete Rome experience. Private tour of the Colosseum and Vatican Museums in one day with lunch break. The ultimate VIP day.",
        highlights: ['Colosseum', 'Vatican Museums', 'City Center', 'Private Guide'],
        includes: ['All Tickets', 'Private Guide', 'Full Day'],
        imageUrl: 'https://images.unsplash.com/photo-1509024644558-2f56ce76c490?w=800&q=80',
        badge: 'VIP',
        rating: 5.0,
        reviews: 80
    },
    {
        id: 'food-tour-trastevere',
        title: 'Trastevere Food & Wine Tour',
        slug: 'trastevere-food-wine-tour',
        category: 'hidden-gems',
        tourType: 'Food Tour',
        price: 85,
        duration: '3 hours',
        description: "Taste the real Rome. Sample pizza, pasta, supplì, gelato, and wine in the charming medieval neighborhood of Trastevere.",
        highlights: ['Local Food', 'Wine Tasting', 'Trastevere Streets', 'Dinner'],
        includes: ['All Food', 'Wine', 'Local Guide'],
        imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80',
        badge: 'Tasty',
        rating: 4.9,
        reviews: 1300
    },
    {
        id: 'hop-on-hop-off',
        title: 'Hop-On Hop-Off Bus + Colosseum',
        slug: 'hop-on-hop-off-colosseum',
        category: 'hidden-gems',
        tourType: 'Bus Tour',
        price: 75,
        duration: '24 hours',
        description: "Combine a 24-hour city bus ticket with a timed entry to the Colosseum. The flexible way to see the city at your own pace.",
        highlights: ['Open Bus', 'Colosseum Entry', 'Flexible Schedule', 'Audio Guide'],
        includes: ['Bus Ticket', 'Colosseum Ticket'],
        imageUrl: 'https://images.unsplash.com/photo-1541370976299-4d24ebbc9070?w=800&q=80',
        rating: 4.4,
        reviews: 2100
    },
    {
        id: 'fountains-squares-sunset',
        title: 'Fountains & Squares at Sunset',
        slug: 'fountains-squares-sunset',
        category: 'city',
        tourType: 'Walking Tour',
        price: 35,
        duration: '2 hours',
        description: "See the city glow during the Golden Hour. Perfect for photography and seeing the Spanish Steps and Pantheon in the best light.",
        highlights: ['Sunset Views', 'Golden Hour', 'Aperitivo Tip'],
        includes: ['Local Guide'],
        imageUrl: 'https://images.unsplash.com/photo-1523554888454-84137e72cea3?w=800&q=80',
        rating: 4.8,
        reviews: 750
    },
    {
        id: 'jewish-ghetto',
        title: 'Jewish Ghetto & Trastevere Walk',
        slug: 'jewish-ghetto-trastevere',
        category: 'city',
        tourType: 'Walking Tour',
        price: 45,
        duration: '2.5 hours',
        description: "Explore one of the oldest Jewish communities in Europe and the bohemian streets of Trastevere. Rich in history and atmosphere.",
        highlights: ['Synagogue (outside)', 'Turtle Fountain', 'Tiber Island'],
        includes: ['Guide', 'Small Group'],
        imageUrl: 'https://images.unsplash.com/photo-1504198266287-1659872e6584?w=800&q=80',
        rating: 4.8,
        reviews: 310
    },
    {
        id: 'aventine-keyhole',
        title: 'Hidden Gems: Aventine Keyhole',
        slug: 'aventine-keyhole-tour',
        category: 'hidden-gems',
        tourType: 'Walking Tour',
        price: 40,
        duration: '2 hours',
        description: "See the famous Keyhole view of St. Peter's, the Orange Garden, and the mouth of Truth. A tour for those who want unique photos.",
        highlights: ['Keyhole View', 'Orange Garden', 'Circus Maximus View'],
        includes: ['Guide'],
        imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
        rating: 4.8,
        reviews: 220
    },
    {
        id: 'villa-borghese',
        title: 'Villa Borghese Gallery & Gardens',
        slug: 'villa-borghese-gallery',
        category: 'city',
        tourType: 'Museum',
        price: 60,
        duration: '2.5 hours',
        description: "Visit the 'Queen of Private Art Collections'. See Bernini statues and Caravaggio paintings in a beautiful park setting.",
        highlights: ['Bernini Sculptures', 'Caravaggio', 'Gardens'],
        includes: ['Ticket', 'Guide'],
        imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
        badge: 'Art Lover',
        rating: 4.9,
        reviews: 800
    },
    {
        id: 'rome-golf-cart-food',
        title: 'Golf Cart Food Tour',
        slug: 'rome-golf-cart-food-tour',
        category: 'hidden-gems',
        tourType: 'Golf Cart/Food',
        price: 180,
        duration: '3.5 hours',
        description: "Combine sightseeing with tasting! Ride a golf cart to the best local food spots for tastings of Roman specialties.",
        highlights: ['Eat & Ride', 'No Walking', 'Best Pizza', 'Wine'],
        includes: ['Cart', 'Driver', 'All Food'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80',
        rating: 5.0,
        reviews: 120
    },
    {
        id: 'pompeii-day-trip',
        title: 'Pompeii & Amalfi Coast Day Trip',
        slug: 'pompeii-amalfi-coast-day-trip',
        category: 'hidden-gems',
        tourType: 'Day Trip',
        price: 160,
        duration: '12 hours',
        description: "Leave Rome for a day to see the ruins of Pompeii and the stunning Amalfi Coast. Includes transport and guided tours.",
        highlights: ['Pompeii Ruins', 'Amalfi Coast Drive', 'Positano view'],
        includes: ['Bus Transport', 'Guide', 'Tickets'],
        imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
        rating: 4.7,
        reviews: 1500
    },
    {
        id: 'tuscany-day-trip',
        title: 'Tuscany Wine Tour Day Trip',
        slug: 'tuscany-wine-tour-day-trip',
        category: 'hidden-gems',
        tourType: 'Day Trip',
        price: 180,
        duration: '10 hours',
        description: "Escape to the rolling hills of Tuscany. Taste majestic wines (Brunello, Chianti) and visit medieval hill towns like Pienza.",
        highlights: ['Wine Tasting', 'Tuscan Landscape', 'Medieval Towns'],
        includes: ['Transport', 'Lunch', 'Wine', 'Guide'],
        imageUrl: 'https://images.unsplash.com/photo-1516528387618-afa90b13e000?w=800&q=80',
        rating: 4.8,
        reviews: 900
    },
    {
        id: 'angels-demons',
        title: 'Angels & Demons Mystery Game',
        slug: 'angels-demons-mystery-game',
        category: 'hidden-gems',
        tourType: 'Game/Walk',
        price: 25,
        duration: '2 hours',
        description: "Follow the path of Illuminati through Rome. A self-guided mystery exploration game based on Dan Brown's novel.",
        highlights: ['Solve Riddles', 'Explore Rome', 'Fun for family'],
        includes: ['App Access'],
        imageUrl: 'https://images.unsplash.com/photo-1473172707857-f9e276582ab6?w=800&q=80',
        rating: 4.5,
        reviews: 200
    }
];
